### ISSUE TITLE
No such file or directory allData.json

### ISSUE THREAD

**Issue by seantoole** [giovannicoppola/AlfreDo#11]
Hello! I've not managed to figure out this issue, have reinstalled the workflow a few times and checked the api key is correct.
Can you assist?

Thanks,

`[18:17:09.111] AlfreDo[Script Filter] Queuing argument 'st'
[18:17:09.257] AlfreDo[Script Filter] Script with argv 'st' finished
[18:17:09.288] ERROR: AlfreDo[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/[username]/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3689F7CF-B665-44CC-80EA-6C403D1A54D3/alfredo_ops.py", line 999, in <module>
    main ()
  File "/Users/[username]/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3689F7CF-B665-44CC-80EA-6C403D1A54D3/alfredo_ops.py", line 995, in main
    parseNewTask (MY_INPUT)
  File "/Users/[username]/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3689F7CF-B665-44CC-80EA-6C403D1A54D3/alfredo_ops.py", line 330, in parseNewTask
    allTasks, mySections, myProjects, myStats, myUser = readTodoistData()
                                                        ^^^^^^^^^^^^^^^^^
  File "/Users/[username]/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3689F7CF-B665-44CC-80EA-6C403D1A54D3/alfredo_ops.py", line 278, in readTodoistData
    with open(MY_DATABASE,'r') as myFile:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/[username]/Library/Application Support/Alfred/Workflow Data/giovanni-alfreDo/allData.json'`

**Comment by giovannicoppola** [comment]
it looks like the task database was not downloaded from todoist. have you tried to force the update with `todoist::refresh`?

**Comment by seantoole** [comment]
That worked! Thanks.
