### ISSUE TITLE
Task creation fails silently when database doesn't exist

### ISSUE THREAD

**Issue by wildmolasses** [giovannicoppola/AlfreDo#26]
i never retrieved tasks via alfred, and was just trying to create a task. however, the task creation would fail silently. after i retrieved tasks via alfredo, the task creation works. cheers!

```
[09:45:20.085] ERROR: AlfreDo[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.66F04A15-FCBA-4E7E-8101-45D1E8AF358F/alfredo_ops.py", line 1147, in <module>
    main ()
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.66F04A15-FCBA-4E7E-8101-45D1E8AF358F/alfredo_ops.py", line 1143, in main
    parseNewTask (MY_INPUT)
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.66F04A15-FCBA-4E7E-8101-45D1E8AF358F/alfredo_ops.py", line 394, in parseNewTask
    allTasks, mySections, myProjects, myStats, myUser = readTodoistData()
                                                        ^^^^^^^^^^^^^^^^^
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.66F04A15-FCBA-4E7E-8101-45D1E8AF358F/alfredo_ops.py", line 279, in readTodoistData
    with open(MY_DATABASE,'r') as myFile:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Library/Application Support/Alfred/Workflow Data/giovanni-alfreDo/allData.json'
```

**Comment by minhaajre** [comment]
Same here. Task creation menu appears but when I add task nothing happens.
