### ISSUE TITLE
Can't execute any ToDoist action, because of JSONDecodeError

### ISSUE THREAD

**Issue by mstuebner** [giovannicoppola/AlfreDo#3]
Fresh installation of Alfred 5.1.2 + Powerpack
Python 3.11 installed

When I enter ! and select any ToDoist action, I get:
----
```
[00:21:53.515] AlfreDo[Script Filter] Queuing argument '(null)'
[00:21:53.623] AlfreDo[Script Filter] Script with argv '(null)' finished
[00:21:53.628] ERROR: AlfreDo[Script Filter] Code 1: 0 days from last update
Traceback (most recent call last):
  File "/Users/mstuebner/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8627439C-3E88-49D0-A5E1-5DBC1AE1C1CC/alfredo-query.py", line 420, in <module>
    main ()
  File "/Users/mstuebner/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8627439C-3E88-49D0-A5E1-5DBC1AE1C1CC/alfredo-query.py", line 28, in main
    allTasks, mySections, myProjects, myStats, myUser = readTodoistData()
                                                        ^^^^^^^^^^^^^^^^^
  File "/Users/mstuebner/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8627439C-3E88-49D0-A5E1-5DBC1AE1C1CC/alfredo_ops.py", line 279, in readTodoistData
    mydata = json.load(myFile)
             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by giovannicoppola** [comment]
@mstuebner it looks like it can't read data from Todoist, could you double check the todoist token?

**Comment by giovannicoppola** [comment]
hello, closing as I assume you solved this. please feel free to let me know if not.

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “Can't execute any ToDoist action, because of JSONDecodeError”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
