### ISSUE TITLE
If there is a timezone in the task's due date, the script fails. 

### ISSUE THREAD

**Issue by jtymes** [giovannicoppola/AlfreDo#9]
```
Traceback (most recent call last):
  File "/Users/jeremy/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.36DB5D48-D6B9-4207-B437-F6CAFF1C35CD/alfredo-query.py", line 421, in <module>
    main ()
  File "/Users/jeremy/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.36DB5D48-D6B9-4207-B437-F6CAFF1C35CD/alfredo-query.py", line 331, in main
    dueDate = datetime.strptime(task ['due']['date'], "%Y-%m-%dT%H:%M:%S")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: Z
```

I fixed this locally by updating `alfredo-query.py` line 331 to include `Z`:

```
dueDate = datetime.strptime(task ['due']['date'], "%Y-%m-%dT%H:%M:%SZ")
```

**Comment by giovannicoppola** [comment]
@jtymes thank you for reporting this, it should be solved in [version 0.4](https://github.com/giovannicoppola/AlfreDo/releases/tag/v0.4). Let me know if you see anything off!
